In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a=np.array([5,6,8])
print(a)

[5 6 8]


In [4]:
type(a)

numpy.ndarray

In [5]:

b=np.array([[9,6,3],[8,6,8],[7,3,4]])
print(b)

[[9 6 3]
 [8 6 8]
 [7 3 4]]


In [6]:
type(b)

numpy.ndarray

In [7]:
b.shape

(3, 3)

In [8]:
a.shape

(3,)

In [9]:
b.dtype

dtype('int32')

In [10]:
type(a)

numpy.ndarray

In [11]:
type(b)

numpy.ndarray

In [12]:
c=([2,4,6])
print(c)

[2, 4, 6]


In [13]:
type(c)

list

In [14]:
d="abc"
type(d)

str

In [15]:
clear

In [16]:
lst1=[i for i in range(15)]
print(lst1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [17]:
lst2=[i+2 for i in range(10)]
print(lst2)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [18]:
lst3=[ x+1 for x in range(2,20,3)]
print(lst3)

[3, 6, 9, 12, 15, 18]


In [19]:
f=[x**2 for x in range(10)]
f


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# creating numpy array

In [22]:
v=np.arange(0,300,5)
print(v)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295]


In [23]:
v*5-2

array([  -2,   23,   48,   73,   98,  123,  148,  173,  198,  223,  248,
        273,  298,  323,  348,  373,  398,  423,  448,  473,  498,  523,
        548,  573,  598,  623,  648,  673,  698,  723,  748,  773,  798,
        823,  848,  873,  898,  923,  948,  973,  998, 1023, 1048, 1073,
       1098, 1123, 1148, 1173, 1198, 1223, 1248, 1273, 1298, 1323, 1348,
       1373, 1398, 1423, 1448, 1473])

In [24]:
np.arange(150,400,15)

array([150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330,
       345, 360, 375, 390])

In [25]:
s=np.arange(2000)
print(s)
s.dtype


[   0    1    2 ... 1997 1998 1999]


dtype('int32')

In [26]:
np.zeros((4,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
k=np.array([[3,2,1],[9,8,7],[6,5,4]])
print(k)

[[3 2 1]
 [9 8 7]
 [6 5 4]]


In [28]:
k.shape

(3, 3)

In [29]:
np.ones((2,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
np.eye(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [31]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
np.full((3,3),2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [33]:
np.full((3,3),5.5,dtype=np.int32)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [34]:
np.zeros_like(k)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
s = np.diag(np.arange(1,50))

In [37]:
s

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  2,  0, ...,  0,  0,  0],
       [ 0,  0,  3, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

In [38]:
# tile
a = np.array([7,8,9]  )
a

array([7, 8, 9])

In [39]:
np.tile(a,(2,2))

array([[7, 8, 9, 7, 8, 9],
       [7, 8, 9, 7, 8, 9]])

In [40]:
b = ([1,2,3],[4,5,6],[7,8,9])
b

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [41]:
np.tile(b,(3,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [42]:
print(np.random.seed())

None


In [43]:
np.random.seed(125)
print(np.random.random())
print(np.random.random())

0.50672601149957
0.05753069516808973


In [44]:
a = np.random.random((3,3))
a

array([[0.62757999, 0.13255253, 0.13108515],
       [0.78854401, 0.50668611, 0.41282608],
       [0.5780087 , 0.48817441, 0.33596388]])

In [45]:
b = np.round(a,3)
b

array([[0.628, 0.133, 0.131],
       [0.789, 0.507, 0.413],
       [0.578, 0.488, 0.336]])

In [46]:
c = b*100
c

array([[62.8, 13.3, 13.1],
       [78.9, 50.7, 41.3],
       [57.8, 48.8, 33.6]])

In [47]:
d = c.astype(np.int32)
d

array([[62, 13, 13],
       [78, 50, 41],
       [57, 48, 33]])

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x.dtype

dtype('int32')

In [50]:
x.itemsize

4

In [51]:
# reshaping
a = np.arange(20)

In [52]:
a.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
x = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [54]:
x.shape

(3, 4)

In [55]:
x.reshape(-1)

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [56]:
x.reshape(1,-1)

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10]])

In [57]:
x.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [58]:
x.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 7,  8],
       [ 9, 10]])

In [59]:
x.reshape(2,-1)

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  7,  7,  8,  9, 10]])

In [60]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
np.arange(24).reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [62]:
# ACCESSING NUMPY ARRAY

In [63]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a[3]

4

In [65]:
a[[1,2,3]]

array([2, 3, 4])

In [66]:
a[2:5]

array([3, 4, 5])

In [67]:
a[0::3]

array([1, 4, 7])

In [68]:
# SUBSET OF ARRAYS
a = np.arange(15)

In [69]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
b = a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
b[2]=15

In [72]:
a

array([ 0,  1, 15,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
np.shares_memory(a,b)

True

In [74]:
b = a.copy()

In [75]:
np.shares_memory(a,b)

False

In [76]:
# Transpose
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [78]:
# stacking
b = np.array([[4,2,1],[1,7,8],[9,8,3]])
b

array([[4, 2, 1],
       [1, 7, 8],
       [9, 8, 3]])

In [79]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 2, 1],
       [1, 7, 8],
       [9, 8, 3]])

In [80]:
np.hstack([a,b])

array([[1, 2, 3, 4, 2, 1],
       [4, 5, 6, 1, 7, 8],
       [7, 8, 9, 9, 8, 3]])

In [81]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [83]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [84]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [85]:
a.std()

2.8722813232690143

In [86]:
a.mean()

4.5

In [87]:
np.median(a)

4.5

In [88]:
a = np.array([1,0,1],dtype=bool)
b = np.array([0,0,1], dtype = bool)
print(a)
print(b)

[ True False  True]
[False False  True]


In [89]:
np.logical_or(a,b)

array([ True, False,  True])

In [90]:
np.logical_and(a,b)

array([False, False,  True])

In [91]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
a.sum(axis=0)

array([5, 7, 9])

In [93]:
a.sum(axis=1)

array([ 6, 15])

In [94]:
a.max()

6

In [95]:
a.argmax()

5

In [96]:
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
b = np.array([[8,52,42],[5,42,66]])
b

array([[ 8, 52, 42],
       [ 5, 42, 66]])

In [98]:
np.sort(b)

array([[ 8, 42, 52],
       [ 5, 42, 66]])

In [99]:
np.argsort(b)

array([[0, 2, 1],
       [0, 1, 2]], dtype=int64)